name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  current_time_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: echo date

  current_directory_job:
    runs-on: ubuntu-latest
    steps:
      - name: Current path
        run: echo ls -l
